import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const conduit = localFont({ src: "../public/fonts/ConduitITC.woff2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Include UTF-8 encoding
    <html lang="en">
      <body className={conduit.className}>{children}</body>
    </html>
  );
}
